apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: zamtok-script-volume
data:
  setup.sh: |
    #!/bin/sh  
    echo "alias vlog='tail -f /storage/zamtok/server.log'" >> ~/.bashrc
    echo "alias vlog='tail -f /storage/zamtok/server.log'" >> ~/.profile
    
    mkdir -p /storage/zamtok
    exec ./server 9000 >> /storage/zamtok/server.log 2>&1
