FROM rockylinux:9

RUN dnf install -y gcc make && dnf clean all

WORKDIR /build/CLIENT

COPY CLIENT /build/CLIENT

RUN mkdir -p /app/bin \
    && make \
    && cp /build/CLIENT/release/CLIENT /app/bin/client \
    && chmod +x /app/bin/client

WORKDIR /app

CMD ["./bin/client"]
